const ben_Beng = {
  wizardSubtitle: 'ব্যক্তিগতকৃত ফসল পরামর্শ পেতে আপনার প্রোফাইল সেট আপ করুন',
  stepLang:     'ভাষা',
  stepIdentity: 'আপনার তথ্য',
  stepLocation: 'অবস্থান',
  stepFarm:     'খামার বিবরণ',
  optional:     '(ঐচ্ছিক)',

  identityTitle:    'আপনার তথ্য',
  identitySubtitle: 'এটি আপনার পরামর্শ অভিজ্ঞতা ব্যক্তিগত করতে সাহায্য করে।',
  nameLabel:        'আপনার নাম',
  namePlaceholder:  'যেমন: রামেশ্বর',
  phoneLabel:       'ফোন নম্বর',
  phonePlaceholder: '১০ সংখ্যার মোবাইল নম্বর',
  nextIdentityBtn:  'পরবর্তী: আপনার অবস্থান →',

  locationTitle:        'আপনার অবস্থান',
  locationSubtitle:     'স্থানীয় আবহাওয়া ও মাটির তথ্যের জন্য আমরা আপনার জেলা ব্যবহার করি।',
  stateLabel:           'রাজ্য',
  statePlaceholder:     '— রাজ্য নির্বাচন করুন —',
  districtLabel:        'জেলা',
  districtPlaceholder:  '— জেলা নির্বাচন করুন —',
  errorState:           'অনুগ্রহ করে আপনার রাজ্য নির্বাচন করুন।',
  errorDistrict:        'অনুগ্রহ করে আপনার জেলা নির্বাচন করুন।',
  errorDistrictNetwork: 'এই জেলা নেটওয়ার্কে নেই। অন্যটি নির্বাচন করুন।',
  backBtn:              '← পিছনে',
  nextLocationBtn:      'পরবর্তী: খামার বিবরণ →',

  farmTitle:       'আপনার খামার',
  farmSubtitle:    'এটি আমাদের মাটি ও সার পরামর্শ দিতে সাহায্য করে।',
  soilLabel:       'মাটির ধরন',
  cropLabel:       'ফসলের জাত',
  cropPlaceholder: 'যেমন: সয়াবিন JS-335',
  stageLabel:      'বৃদ্ধির পর্যায়',
  errorSoil:       'অনুগ্রহ করে মাটির ধরন নির্বাচন করুন।',
  errorCrop:       'অনুগ্রহ করে ফসলের জাত লিখুন (ন্যূনতম ২ অক্ষর)।',
  errorStage:      'অনুগ্রহ করে বৃদ্ধির পর্যায় নির্বাচন করুন।',
  submitBtn:       'পরামর্শ শুরু করুন →',
  submittingBtn:   'প্রস্তুত হচ্ছে…',

  soilClay:     { label: 'এঁটেল মাটি',   desc: 'ভারী, জলধারক' },
  soilLoamy:    { label: 'দোআঁশ মাটি',   desc: 'সুষম, উর্বর' },
  soilSandy:    { label: 'বালু মাটি',    desc: 'হালকা, দ্রুত নিষ্কাশন' },
  soilBlack:    { label: 'কালো মাটি',    desc: 'খনিজ সমৃদ্ধ, আর্দ্রতা ধারক' },
  soilRed:      { label: 'লাল মাটি',     desc: 'আয়রন সমৃদ্ধ, দ্রুত নিষ্কাশন' },
  soilAlluvial: { label: 'পলি মাটি',     desc: 'নদীবাহিত, অত্যন্ত উর্বর' },
  soilLaterite: { label: 'ল্যাটেরাইট',   desc: 'কঠিন, আয়রন অক্সাইড সমৃদ্ধ' },

  stageSowing:       { label: 'বপন',          desc: 'বীজ রোপণ' },
  stageGermination:  { label: 'অঙ্কুরোদগম',   desc: 'চারা গজানো' },
  stageVegetative:   { label: 'উদ্ভিজ্জ',    desc: 'পাতা ও কাণ্ড বৃদ্ধি' },
  stageFlowering:    { label: 'ফুল ধরা',     desc: 'ফুল ও পরাগায়ন' },
  stageFruiting:     { label: 'ফল ধরা',      desc: 'ফল ও দানা পূর্ণ হওয়া' },
  stageHarvesting:   { label: 'ফসল কাটা',    desc: 'ফসল সংগ্রহ' },

  greeting: 'নমস্কার! আমি CropCompass — আপনার ফসল পরামর্শদাতা।\nআপনার ফসল সম্পর্কে যেকোনো প্রশ্ন জিজ্ঞাসা করুন।',

  phaseGather:    'আপনার প্রোফাইল ও আবহাওয়ার পূর্বাভাস দেখা হচ্ছে…',
  phaseGenerate:  'আপনার পরামর্শ তৈরি করা হচ্ছে…',
  phaseVerify:    'জ্ঞানভাণ্ডারের সাথে পরামর্শ যাচাই করা হচ্ছে…',
  phaseTranslate: 'আপনার ভাষায় অনুবাদ করা হচ্ছে…',

  toolGetProfile:    'আপনার প্রোফাইল লোড হচ্ছে…',
  toolFetchAdvisory: 'আবহাওয়ার পূর্বাভাস পরীক্ষা করা হচ্ছে…',
  toolQueryKb:       'ফসল জ্ঞানভাণ্ডারে অনুসন্ধান করা হচ্ছে…',
  toolTranslate:     'উত্তর অনুবাদ করা হচ্ছে…',

  micLabel:      'আপনার প্রশ্ন বলুন',
  listenLabel:   'শুনুন',
  stopLabel:     'থামুন',
  autoReadLabel: 'উত্তর স্বয়ংক্রিয়ভাবে পড়ুন',

  suggestions: [
    'আমার ফসল কখন বপন করব?',
    'আমার ফসলের কতটা জল দরকার?',
    'এখন কোন সার দেওয়া উচিত?',
    'আবহাওয়ার পূর্বাভাস কী?',
  ],
}

export default ben_Beng
